### ISSUE TITLE
Wrong Euler Angle.

### ISSUE THREAD

**Issue by tonvanhieu** [EmanuelFeru/hoverboard-sideboard-hack-GD#5]
I saw that Euler angles that calculate from DMP are so wrong.

When i checked with 3D Visualization Demo, the angle rotated more about 8 times than reality.

I saw your clip upload on Telegram, it's so cool and smooth.
 
Have you ever meet that behavior? Please help me teacher.

I have sent you a short clip on telegram, please accept my request (https://t.me/tonvanhieu)

**Comment by EFeru** [comment]
If you check with Debug variant, the angles are OK. The visualization needs more work.. 
The Serial read in the visualization is not that great. It is not that easy to read out pure integers from serial because is in Java. The visualization would work better if we send text separated by a space or other delimiter. This can be more easily proceessed by the tool.

Now that you mentioned I think is better to use the Visualization with debug variant, send 'e' from Processing and read out the angles. 

I could not see your video. Is better to send me a private message directly in telegram.

**Comment by tonvanhieu** [comment]
> If you check with Debug variant, the angles are OK. The visualization needs more work..

You are right, the angles in Debug variant is much better. I'll try to use the Visualization again with the debug variant as you say.

> I could not see your video. Is better to send me a private message directly in telegram.

I dont't know why but my account cant send message to another contact. Maybe a mistake. I have sent Telegram a complaint.

**Comment by EFeru** [comment]
> I dont't know why but my account cant send message to another contact. Maybe a mistake. I have sent Telegram a complaint.

I use the app on my phone and PC. They both work well.

**Comment by EFeru** [comment]
@tonvanhieu , I fixed it .. works perfectly now :) I will commit the sketch in 15min with other stuff too.
